app/models.py
from sqlalchemy.orm import backref
from .app import db

class Personne(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    prenom = db.Column(db.String(50))
    nom = db.Column(db.String(50))
    dateNaissance = db.Column(db.Date()) 
    dateDeces = db.Column(db.Date())
    etatCivil = db.Column(db.Text())
    descendancePersonne = db.Column(db.Text())

    def __repr__(self):
        return "<Personne (%d) %s %s>" % (self.id, self.prenom, self.nom)

class Sauveteur(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    idPersonne = db.Column(db.Integer, db.ForeignKey("personne.id"))
    personne = db.relationship("Personne", uselist=False)

    def __repr__(self):
        return "<Sauveteur (%d) %s %s>" % (self.id, self.personne.nom, self.personne.prenom)

class Equipage(db.Model):
    id = db.Column(db.Integer, primary_key=True)

class Appartenir(db.Model):
    idSauveteur = db.Column(db.Integer, db.ForeignKey("sauveteur.id") , primary_key=True)
    sauveteur = db.Column("Equipage", backref = db.backref("books"), lazy="dynamic"),  


    

app/snsm_app/models/database.py
from typing import List
from sqlite3 import Connection


class Personne(object):
    def __init__(self, id, nom, prenom, date_naissance, date_mort, etat_civil, descendance):
        self.id = id
        self.nom = nom
        self.prenom = prenom
        self.date_naissance = date_naissance
        self.date_mort = date_mort
        self.etat_civil = etat_civil
        self.descendance = descendance


class Sauveteur(object):
    def __init__(self, id, personne):
        self.id = id
        self.personne = personne


class Bateau:
    def __init__(self, id, typeB, nom):
        self.id = id
        self.type = typeB
        self.nom = nom

    def __repr__(self):
        return str(self.id) + " " + self.type + " " + self.nom


def get_sauveteurs(conn: Connection) -> List[Sauveteur]:
    c = conn.execute("SELECT * FROM SAUVETEUR NATURAL JOIN PERSONNE")
    personnes = list()
    for row in c:
        personnes.append(Sauveteur(
            row[0],
            Personne(
                row[1],
                row[2],
                row[3],
                row[4],
                row[5],
                row[6],
                row[7]
            )))
    c.close()
    return personnes


def get_bateaux(conn):
    bateaux = list()
    data = conn.execute("select * from bateau")
    for raw in data:
        bateaux.append(Bateau(raw[0], raw[1], raw[2]))
    return bateaux


def insert_user(conn, username, email, password):
    print(conn.execute("INSERT INTO UTILISATEUR (username, passwordUser, emailUser, roleUtilisateur) VALUES(:username, :password, :email, :role)",
                 {"username": username, "password": password, "email": email, "role": "U"}).fetchone())

app/snsm_app/models/forms/auth.py
from wtforms import Form, StringField, PasswordField, validators


class LoginForm(Form):
    username = StringField("Nom d'utilisateur",  [
        validators.DataRequired(),
    ])
    password = PasswordField('Mot de passe', [
        validators.DataRequired(),
    ])

class RegisterForm(Form):
    username = StringField("Nom d'utilisateur",  [
        validators.DataRequired(),
    ])
    password = PasswordField('Mot de passe', [
        validators.DataRequired(),
    ])
    email = PasswordField('Adresse email', [
        validators.DataRequired(),
    ])

app/__init__.py
"""
    Permet de créer l'application.
"""


import os
import sqlite3
import traceback
from flask import Flask
from sqlalchemy.pool import StaticPool
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker, scoped_session

try:
    from .snsm_app.views import index
    from .snsm_app.commands import bp
except:
    traceback.print_last()


def create_app():
    """
        Créer l'application
    """
    app = Flask(__name__)

    app.register_blueprint(index)
    app.register_blueprint(bp)

    app.config['DB'] = create_engine(os.environ.get(
        'DATABASE_URL'), poolclass=StaticPool, echo = True)
    session_factory = sessionmaker(bind=app.config['DB'])
    app.config['SESSION'] = scoped_session(session_factory)
    return app

app/app.py
from flask import Flask, render_template
app = Flask(__name__)


@app.route("/bateau")
def bateau():
    return render_template(
        "bateau.html",
        title = "bonjour à tous les amis 2",
        personnage_pas_important = {"Patron":"NomPatron","Sous-Patron":"Nom du Sous-patron","armement":["Nom1", "Nom2", "Nom3"]},  
        DATE = "01/01/01",
        STATS_VIE = {"mort": 2, "vivant": 3},
        NOM_BATEAU = "LES TROIS SOEURS"
        )


if __name__ == "__main__":
    app.run()

app/snsm_app/views.py
from flask import render_template
from flask.helpers import url_for
from .models.forms.auth import LoginForm, RegisterForm
from .models.database import get_sauveteurs, insert_user, get_bateaux

from flask import Blueprint, render_template, redirect, request, current_app

import hashlib

index = Blueprint('index', __name__, url_prefix="/")


@index.route("/")
def hello():
    return render_template(
        "main.html",
        title="bonjour à tous les amis 2")


@index.route("/login", methods=['GET', 'POST'])
def login():
    form = LoginForm(request.form)
    if request.method == 'POST' and form.validate():
        return redirect('/')
    return render_template('login.html', form=form, title="Se connecter")


@index.route("/register", methods=['GET', 'POST'])
def register():
    form = RegisterForm(request.form)
    if request.method == 'POST' and form.validate():
        content = hashlib.sha256(form.password.data.encode()).hexdigest()
        s = current_app.config['SESSION']
        insert_user(s, form.username.data, form.email.data, content)
        s.remove()
        return redirect(url_for("index.login"))
    return render_template('register.html', form=form, title="S'inscrire")


@index.route("/logout")
def logout():
    return "TODO LOGOUT"


@index.route("/bateaux")
def bateaux():
    s = current_app.config['SESSION']
    batals = get_bateaux(s)
    s.remove()
    return render_template(
        "corps_pages.html",
        title="Bateaux",
        bateaux=batals
    )


@index.route("/bateau/<int:id>")
def bateau(id):
    return render_template(
        "bateau.html",
        title="Bateaux - %d" % id,
        personnage_pas_important={
            "Patron": "NomPatron", "Sous-Patron": "Nom du Sous-patron", "armement": ["Nom1", "Nom2", "Nom3"]},
        DATE="01/01/01",
        STATS_VIE={"mort": 2, "vivant": 3},
        NOM_BATEAU="LES TROIS SOEURS"
    )


@index.route("/sauvetages")
def sauvetages():
    return "TODO"


@index.route("/sauveteurs")
def sauveteurs():
    s = current_app.config['SESSION']
    sauveteurs = get_sauveteurs(s)
    s.remove()
    return render_template(
        "sauveteurs.html",
        title="Les sauveteurs",
        sauveteurs=sauveteurs
    )



@index.route("/sauveteur/<int:id>")
def sauveteur(id):
    s = current_app.config['SESSION']
    sauveteurs = get_sauveteurs(s)
    s.remove()
    return render_template(
        "sauveteurs.html",
        title="Les sauveteurs",
        sauveteurs=sauveteurs
    )

@index.route("/personne/<int:id>")
def personne(id):
    return "<h1>%d</h1>" % id


@index.route("/sauvetage/<int:id>")
def sauvetage(id):
    return "<h1>%d</h1>" % id

app/templates/_formhelpers.html
{% macro render_field(field) %}
<dt>{{ field.label }}
<dd>{{ field(**kwargs)|safe }}
    {% if field.errors %}
    <ul class=errors>
        {% for error in field.errors %}
        <li>{{ error }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</dd>
{% endmacro %}

app/templates/bateau.html
{% extends "home.html" %}
{% block content %}
<section class="sec_bateau">
    <h1>{{ title }}</h1>
        <div class="bateau_legende_img">
            <img src="../static/images/banniere-test.jpg" alt="banniere"/>
            <div>
                <h2>Sauvetage du bateau {{NOM_BATEAU}}</h2>
            </div>
        </div>
        <div class="infos_bateaux">
            <ul>
                <li>
                    <h4>Patron du canot</h4><br>
                    <p><a>{{personnage_pas_important['Patron']}}</a></p>
                </li>
            </ul>
            <ul>
                <li>
                    <h4>Sous-patron</h4><br>
                    <p><a>{{personnage_pas_important['Sous-Patron']}}</a></p>
                </li>
            </ul>
            <ul>
                <li>
                    <h4>Armement</h4><br>
                    {% for elem in personnage_pas_important['armement'] %}
                    <p><a>{{elem}}</a></p>
                    {% endfor %}
                </li>
            </ul>
            </ul>
            <ul>
                <li>
                    <h4>Date : {{DATE}}</h4><br>
                    <p>Nombres de personnes décédés {{STATS_VIE['mort']}}, Nombres de personnes sauvés {{STATS_VIE['vivant']}}</p>
                </li>
            </ul>
        </div>
</section>
{% endblock %}

app/templates/corps_pages.html
{% extends "home.html" %}
{% block content %}
<section style="text-align: center; margin: 1em;">
  <a href="https://fr.wikipedia.org/wiki/Station_spatiale_internationale#:~:text=La%20Station%20spatiale%20internationale%20est,environ%20420%20tonnes%20en%202019." target="_blank"><img class="logo_entete" src="{{ url_for('static', filename='images/iss.png') }}"/></a>
</section>
<ul>
  {% for batal in bateaux %}
  <li><a href="{{ url_for('index.bateau', id = batal.id) }}">{{ batal }}</a></li>
  {% endfor %}
</ul>

{% endblock %}

app/templates/home.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='home.css') }}">
    <link rel="icon" type="image/png" href="{{ url_for('static', filename='images/THOMAS.jpg') }}">
    <!-- TODO OPTIMISE -->
</head>

<body>
<header id="haut">
    <div>
        <form method="get" action="{{ url_for('index.hello') }}">
            <input type="image" class="logo_entete" alt="logo_corsaires_dunkerquois" src="{{ url_for('static', filename='images/corsaires_dunkerquois.jpg') }}">
            <input type="image" class="logo_entete" alt="logo_sauveteurs_dunkerquois" src="{{ url_for('static', filename='images/sauveteurs_dunkerquois.png') }}">
        </form>
    </div>
    <div class="titre_site">
        <h1>Sauveteurs du Dunkerquois</h1>
        <h3>270 ans d'histoire</h3>
    </div>
</header>
<nav>
    <ul>
        <li><a href="{{ url_for('index.bateaux') }}">Bateaux</a></li>
        <li><a href="{{ url_for('index.sauvetages') }}">Sauvés</a></li>
        <li><a href="{{ url_for('index.sauveteurs') }}">Sauveteurs</a></li>
    </ul>
    <ul>
        <form method="GET" action="https://fr.wikipedia.org/wiki/Thomas_Pesquet">
            <input type="search" placeholder="Rechercher un bateau, sauveteur ou rescapé"/>
            <input class="submit_form" type="image" src="../static/images/loupe.png" alt="Submit Form" />
        </form>
    </ul>
</nav>
<main>
    {% block content %}{% endblock %}
    <div class="div_fusee"><a href="#haut"><img class="fusee" src="{{ url_for('static', filename='images/fusee.png') }}"/></a></div>
</main>
</body>
<footer>
    <img src="../static/images/logo_snsm.svg.png"/>
    <ul>
        <li><a href="/">Qui sommes-nous ?</a></li>
        <li><a href="https://www.facebook.com/groups/938396409644949">Facebook</a></li>
        <li><a href="https://twitter.com/@boutelierphili1">Twitter</a></li>
    </ul>
</footer>
</html>

app/templates/login.html
{% extends "home.html" %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<form method=post>
    <dl>
        {{ render_field(form.username) }}
        {{ render_field(form.password) }}
    </dl>
    <p><input type=submit>
</form>

{% endblock %}

app/templates/main.html
{% extends "home.html" %}
{% block content %}

<section style="text-align: center; padding: 2em;">
    <a href="https://fr.wikipedia.org/wiki/Thomas_Pesquet" target="_blank"><img src="{{ url_for('static', filename='images/THOMAS.jpg') }}"/></a>
</section>

{% endblock %}

app/templates/register.html
{% extends "home.html" %}
{% block content %}
{% from "_formhelpers.html" import render_field %}
<form method=post>
    <dl>
        {{ render_field(form.username) }}
        {{ render_field(form.email) }}
        {{ render_field(form.password) }}
    </dl>
    <p><input type=submit>
</form>

{% endblock %}

app/templates/sauve.html
{% extends "home.html" %}
{% block content %} 
<section>
    {%for elem in desc%}
    <p>{{ elem }}</p>
    {% endfor%}
    <img src="{{ url_for('static', filename='') }}" alt="image de la personne sauve">
</section>
<section>
    textaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
</section>
{% endblock %}

app/templates/sauveteur.html
{% extends "home.html" %}
{% block content %}
{% for desc in pr %}
<p class="Petites Infos">{{ desc }}</p>
{% endfor %}
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Ficquet-Pierre-Portrait.png') }}">
<img alt="image_sauveur"
    src="{{ url_for('static', filename='images/Decoration-Ordre-de-la-couronne-dAllemagne.png') }}">
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Decoration-medaille-argent-brittanique.png') }}">
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Decoration-Legion-d-Honneur-1.png') }}">
{% for x in names %}
<p>{{ x }}</p>
{% endfor %}
{% for (date,dico) in section1.items() %}
<h2>{{ date[0] }}</h2>
<p>{{ date[1] }}</p>
{% for prg in dico.values() %}
<p>{{ prg }}</p>
{% endfor %}
{% endfor %}
{% endblock %}

app/templates/sauveteurs.html
{% extends "home.html" %}
{% block content %}
{% for desc in pr %}
<p class="Petites Infos">{{ desc }}</p>
{% endfor %}
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Ficquet-Pierre-Portrait.png') }}">
<img alt="image_sauveur"
    src="{{ url_for('static', filename='images/Decoration-Ordre-de-la-couronne-dAllemagne.png') }}">
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Decoration-medaille-argent-brittanique.png') }}">
<img alt="image_sauveur" src="{{ url_for('static', filename='images/Decoration-Legion-d-Honneur-1.png') }}">
<ul>
{% for s in sauveteurs %}
<li>{{s.personne.nom}}</li>
{% endfor %}
</ul>
{% endblock %}